services:
  web:
    build:
      context: ./apps/web
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-https://buildaneuralnet-production.up.railway.app}
    command: pnpm dev

  api:
    build:
      context: ./apps/api
    ports:
      - "8000:8000"
    volumes:
      - ./apps/api:/app
    env_file:
      - ./apps/api/.env  # Load environment variables from API .env file
    environment:
      # 🔒 SECURE: Use environment variables instead of hardcoded secrets
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./nn_builder.db}

      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-https://www.buildaneural.net,https://buildaneuralnet-production.up.railway.app,https://buildaneural.net}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-www.buildaneural.net,buildaneuralnet-production.up.railway.app,buildaneural.net,localhost,127.0.0.1}
      # 🔒 SECURE: Email configuration loaded from environment variables
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - FRONTEND_URL=${FRONTEND_URL:-https://www.buildaneural.net}
      # Security configuration
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DEBUG=${DEBUG:-false}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - RATE_LIMIT_PER_MINUTE=${RATE_LIMIT_PER_MINUTE:-60}
      - AUTH_RATE_LIMIT_PER_MINUTE=${AUTH_RATE_LIMIT_PER_MINUTE:-5}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
